### ISSUE TITLE
iPhone Plus横屏启动App，时间状态会继续横着

### ISSUE THREAD

**Issue by CrassusX** [lixiaonan/LMIJKPlayer#4]

**Comment by lixiaonan** [comment]
@crassusxst 你好, 我修改了项目的横竖屏配置, 在appDelegate中配置了项目支持的屏幕方向, 修复了你说的这个问题.

**Comment by CrassusX** [comment]
这中解决方案很6，另外咨询下你的这些项目有在AppStore上线的不，看看
